"""Canonical structured policies for the Client Service Decision Slice.

Compiled from the private corpus's 23 natural-language decision rules
(slice_root/policies/decision_policies.yaml) and the 10 policy regression
tests (slice_root/policies/policy_tests.yaml). Each Policy carries the same
id as the source rule (POL-C-*) so deterministic tests can assert on the
original ids, plus structured trigger features, the §30 strategy, the closed
action vocabulary, the §32 approval level and the §31 disclosure ceiling.

Business judgment is encoded here — edit deliberately and version it; this is
the public compile of private doctrine, so rules stay behavioral, never
customer-identifying. When the private corpus bumps, re-derive this file and
re-run the regression tests.
"""

from __future__ import annotations

from .models import Policy

# Trigger feature vocabulary (assess_customer emits these):
#   paid, prior_disclosure, request, asks_case, asks_price, asks_full_solution,
#   authority, budget, prompt_changes_failed, existing_stack, software_need,
#   scale_signal, meeting_request, real_failure_sample, corpus_reuse,
#   repeat_consulting, goal, method_validated, root_cause_unclear

CANONICAL_POLICIES: list[Policy] = [
    Policy(
        policy_id="POL-C-001",
        name="pre_sales_disclosure_boundary",
        rule_summary="未付费且已解释过方向后，继续索取具体实现时，只给原则/边界，完整方法进入付费诊断或项目。",
        trigger={
            "paid": [False],
            "prior_disclosure": ["high"],
            "request": ["implementation_details"],
        },
        judgment="restrict_disclosure_to_boundary",
        strategy="QUALIFY_BEFORE_DISCLOSE",
        preferred_actions=["explain_principle", "explain_boundary", "propose_paid_diagnosis"],
        restricted_actions=["full_implementation_plan", "complete_workflow", "custom_architecture", "generate_custom_solution"],
        approval_level="R2",
        disclosure_ceiling="D2",
        evidence_ids=[
            "EVD-G-0019", "EVD-G-0024", "EVD-G-0027", "EVD-G-0041", "EVD-G-0092",
            "EVD-G-0119", "EVD-G-0120", "EVD-G-0124", "EVD-G-0125", "EVD-G-0228",
        ],
    ),
    Policy(
        policy_id="POL-C-002",
        name="repeated_free_consulting_reduce_density",
        rule_summary="连续多轮索取技术/方案信息但没有对等采购信号时，缩短回复并停止主动科普。",
        trigger={
            "paid": [False],
            "prior_disclosure": ["high"],
        },
        judgment="reduce_density",
        strategy="RESTRICT_DISCLOSURE",
        preferred_actions=["shorten_reply", "stop_proactive_education"],
        restricted_actions=["full_implementation_plan", "complete_workflow", "schedule_meeting"],
        approval_level="R1",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0026", "EVD-G-0030", "EVD-G-0031", "EVD-G-0033", "EVD-G-0035"],
    ),
    Policy(
        policy_id="POL-C-003",
        name="technical_topic_back_to_business_outcome",
        rule_summary="模型/工具讨论偏离核心问题时，转回内容标准、素材、样本、审核与业务结果。",
        trigger={"request": ["technical_debate"]},
        judgment="refocus_business_outcome",
        strategy="EXPLAIN_GENERAL_DIRECTION",
        preferred_actions=["refocus_business_outcome", "explain_principle"],
        restricted_actions=["full_implementation_plan", "custom_architecture"],
        approval_level="R1",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0004", "EVD-G-0005", "EVD-G-0015", "EVD-G-0036", "EVD-G-0050"],
    ),
    Policy(
        policy_id="POL-C-004",
        name="standard_before_prompt_reviewer_or_agent",
        rule_summary="Prompt 反复无效或客户想搭审核 Agent 时，先建立评价标准与参考样本，再决定自动化。",
        trigger={"prompt_changes_failed": [True]},
        judgment="standards_before_automation",
        strategy="QUALIFY_NEED",
        preferred_actions=["collect_real_samples", "define_L2_scope", "propose_paid_diagnosis"],
        restricted_actions=["complete_workflow", "custom_architecture", "full_implementation_plan"],
        approval_level="R1",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0021", "EVD-G-0025", "EVD-G-0031", "EVD-G-0050"],
    ),
    Policy(
        policy_id="POL-C-005",
        name="diagnose_before_full_system",
        rule_summary="客户提出整套系统/流程时，先做真实样本诊断和小范围验证，方法有效后再进入流程/系统实施。",
        trigger={"asks_full_solution": [True]},
        judgment="diagnose_before_system",
        strategy="QUALIFY_BEFORE_DISCLOSE",
        preferred_actions=["propose_paid_diagnosis", "collect_real_samples", "validate_method_on_samples"],
        restricted_actions=["full_implementation_plan", "complete_workflow", "custom_architecture"],
        approval_level="R2",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0004", "EVD-G-0025", "EVD-G-0041", "EVD-G-0118"],
    ),
    Policy(
        policy_id="POL-C-006",
        name="case_request_triggers_qualification",
        rule_summary="客户索要成功案例且决策权/预算/服务层级不清时，先做资格审查，再决定披露哪些案例材料。",
        trigger={
            "asks_case": [True],
            "authority": ["unknown"],
        },
        judgment="qualify_before_case_disclosure",
        strategy="QUALIFY_BEFORE_DISCLOSE",
        preferred_actions=["clarify_decision_authority", "explain_general_direction"],
        restricted_actions=["send_detailed_case", "full_case_disclosure"],
        approval_level="R2",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0024", "EVD-G-0092", "EVD-G-0119", "EVD-G-0124"],
    ),
    Policy(
        policy_id="POL-C-007",
        name="low_ticket_no_meeting",
        rule_summary="潜在需求低于约 ¥15,000 时，不默认投入视频会议/线下会议；优先异步文字和小型付费诊断。",
        trigger={"budget": ["low"]},
        judgment="async_first",
        strategy="QUALIFY_BUDGET",
        preferred_actions=["async_text_only", "propose_paid_diagnosis"],
        restricted_actions=["schedule_meeting"],
        approval_level="R1",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0119", "EVD-G-0125", "EVD-G-0138"],
    ),
    Policy(
        policy_id="POL-C-008",
        name="business_scale_controls_service_tier",
        rule_summary="业务规模、长期性、真实样本和组织投入显著增加时，机会可上调服务层级；不能只看聊天热度。",
        trigger={"scale_signal": ["very_large"]},
        judgment="tier_upgrade_potential",
        strategy="QUALIFY_AUTHORITY",
        preferred_actions=["light_due_diligence", "clarify_decision_authority"],
        restricted_actions=["schedule_meeting"],
        approval_level="R2",
        disclosure_ceiling="D3",
        evidence_ids=["EVD-G-0001", "EVD-G-0002", "EVD-G-0025", "EVD-G-0030"],
    ),
    Policy(
        policy_id="POL-C-009",
        name="abnormal_scale_requires_light_due_diligence",
        rule_summary="客户披露异常大的业务规模时，允许做轻量主体/业务模式核验，再决定高成本售前或交付承诺。",
        trigger={"scale_signal": ["very_large"]},
        judgment="light_due_diligence",
        strategy="QUALIFY_AUTHORITY",
        preferred_actions=["light_due_diligence", "clarify_budget"],
        restricted_actions=["commit_to_contract", "promise_delivery", "schedule_meeting"],
        approval_level="R2",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0018", "EVD-G-0030", "EVD-G-0031"],
    ),
    Policy(
        policy_id="POL-C-010",
        name="preserve_viable_existing_stack",
        rule_summary="已有软件/LLM 链可用且客户当前不需要软件时，优先改内容标准、素材和审核，不推动重构。",
        trigger={
            "existing_stack": [True],
            "software_need": ["not_now"],
        },
        judgment="preserve_stack",
        strategy="EXPLAIN_GENERAL_DIRECTION",
        preferred_actions=["focus_content_standard", "explain_principle"],
        restricted_actions=["rearchitecture", "push_agent_software"],
        approval_level="R1",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0004", "EVD-G-0025", "EVD-G-0050"],
    ),
    Policy(
        policy_id="POL-C-011",
        name="reject_pure_software_outsourcing",
        rule_summary="若机会实质变成纯软件开发外包，不按当前服务模型承接；保持咨询/诊断/验证/落地边界。",
        trigger={"request": ["software_outsourcing"]},
        judgment="decline_outsourcing",
        strategy="DECLINE_COMMITMENT",
        preferred_actions=["explain_boundary", "explain_tradeoff"],
        restricted_actions=["accept_software_outsourcing", "commit_to_contract"],
        approval_level="R2",
        disclosure_ceiling="D1",
        evidence_ids=["EVD-G-0021", "EVD-G-0041", "EVD-G-0118"],
    ),
    Policy(
        policy_id="POL-C-012",
        name="L1_is_bounded_real_failure_diagnostic",
        rule_summary="L1 用少量真实问题稿及其来源证据做快速诊断和 Before/After，不在聊天里免费完成根因分析。",
        trigger={"real_failure_sample": [True]},
        judgment="bounded_l1_diagnostic",
        strategy="PROPOSE_PAID_DIAGNOSIS",
        preferred_actions=["define_L1_scope", "collect_real_samples"],
        restricted_actions=["full_root_cause_in_chat", "definitive_prescription"],
        approval_level="R1",
        disclosure_ceiling="D3",
        evidence_ids=["EVD-G-0098", "EVD-G-0099", "EVD-G-0110"],
    ),
    Policy(
        policy_id="POL-C-013",
        name="L2_for_root_cause_and_standard",
        rule_summary="当素材、结构、风格或审核根因不清时进入 L2，以真实正反样本建立问题分类、内容标准和审核规则。",
        trigger={"root_cause_unclear": [True]},
        judgment="enter_l2_scope",
        strategy="QUALIFY_NEED",
        preferred_actions=["define_L2_scope", "collect_real_samples"],
        restricted_actions=["full_implementation_plan"],
        approval_level="R1",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0025", "EVD-G-0031", "EVD-G-0110"],
    ),
    Policy(
        policy_id="POL-C-014",
        name="L3_validates_method_on_real_samples",
        rule_summary="L3 的目标是用真实业务样本验证新方法和标准，而不是证明模型会不会写。",
        trigger={"method_validated": [False]},
        judgment="validate_method",
        strategy="PROPOSE_PAID_DIAGNOSIS",
        preferred_actions=["validate_method_on_samples", "collect_real_samples"],
        restricted_actions=["full_implementation_plan", "complete_workflow"],
        approval_level="R1",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0025", "EVD-G-0118"],
    ),
    Policy(
        policy_id="POL-C-015",
        name="L4_L5_only_after_method_validation",
        rule_summary="流程落地与系统集成只能建立在已经通过真实样本验证的方法之上。",
        trigger={
            "method_validated": [False],
            "asks_full_solution": [True],
        },
        judgment="defer_integration",
        strategy="QUALIFY_BEFORE_DISCLOSE",
        preferred_actions=["validate_method_on_samples", "define_L2_scope"],
        restricted_actions=["full_implementation_plan", "complete_workflow", "custom_architecture"],
        approval_level="R2",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0025", "EVD-G-0036", "EVD-G-0118"],
    ),
    Policy(
        policy_id="POL-C-016",
        name="platform_external_outcomes_not_guaranteed",
        rule_summary="不承诺封号、流量恢复、AI 检测率等平台控制之外结果；平台变化通过持续适配处理。",
        trigger={"request": ["platform_guarantee"]},
        judgment="decline_outcome_guarantee",
        strategy="DECLINE_COMMITMENT",
        preferred_actions=["explain_boundary", "explain_principle"],
        restricted_actions=["guarantee_outcomes", "commit_to_contract"],
        approval_level="R2",
        disclosure_ceiling="D1",
        evidence_ids=["EVD-G-0006", "EVD-G-0018", "EVD-G-0098"],
    ),
    Policy(
        policy_id="POL-C-017",
        name="needs_unclear_ask_target_before_solution",
        rule_summary="需求目标不清时，不替客户提前设计方案；先让客户描述业务目标、预期效果和当前约束。",
        trigger={
            "goal": ["unclear"],
            "asks_full_solution": [True],
        },
        judgment="ask_target_first",
        strategy="REQUEST_MORE_CONTEXT",
        preferred_actions=["ask_business_goal", "clarify_budget"],
        restricted_actions=["full_implementation_plan", "custom_architecture", "generate_custom_solution"],
        approval_level="R1",
        disclosure_ceiling="D1",
        evidence_ids=["EVD-G-0015", "EVD-G-0041", "EVD-G-0118"],
    ),
    Policy(
        policy_id="POL-C-018",
        name="software_not_now_focus_content_standard",
        rule_summary="客户明确软件暂时不要时，当前机会聚焦 L2 内容/素材标准与诊断，不继续推 Agent/软件。",
        trigger={"software_need": ["not_now"]},
        judgment="focus_content_standard",
        strategy="EXPLAIN_GENERAL_DIRECTION",
        preferred_actions=["focus_content_standard", "define_L2_scope"],
        restricted_actions=["push_agent_software", "rearchitecture"],
        approval_level="R1",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0004", "EVD-G-0025"],
    ),
    Policy(
        policy_id="POL-C-019",
        name="corpus_reuse_is_diagnostic_variable",
        rule_summary="大量复用素材、母稿和结构时，诊断必须覆盖素材来源、结构复用和批次相似性，不能只做措辞去 AI 味。",
        trigger={"corpus_reuse": ["high"]},
        judgment="include_reuse_in_diagnosis",
        strategy="QUALIFY_NEED",
        preferred_actions=["collect_real_samples", "define_L2_scope"],
        restricted_actions=["definitive_prescription"],
        approval_level="R1",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0110", "EVD-G-0118"],
    ),
    Policy(
        policy_id="POL-C-020",
        name="partial_framework_can_support_quote_without_full_method",
        rule_summary="进入价格/能力验证阶段时，可展示报价与有限框架截图建立可信度，但不交完整运营方法包。",
        trigger={
            "asks_price": [True],
            "prior_disclosure": ["medium", "high"],
        },
        judgment="quote_with_boundary",
        strategy="EXPLAIN_GENERAL_DIRECTION",
        preferred_actions=["show_tiered_quote", "explain_boundary"],
        restricted_actions=["full_implementation_plan", "complete_workflow"],
        approval_level="R2",
        disclosure_ceiling="D3",
        evidence_ids=["EVD-G-0120", "EVD-G-0125", "EVD-G-0138"],
    ),
    Policy(
        policy_id="POL-C-021",
        name="direct_price_request_show_tiered_quote",
        rule_summary="客户直接问价格时，可以给分级参考报价；询价本身不等于预算匹配或有决策权。价格仍需真实付费项目持续校准（含语料库 POL-C-023 校准约束），避免把参考价当成熟定价模型。",
        trigger={"asks_price": [True]},
        judgment="tiered_quote",
        strategy="EXPLAIN_GENERAL_DIRECTION",
        preferred_actions=["show_tiered_quote", "clarify_decision_authority", "explain_tradeoff"],
        restricted_actions=["commit_to_contract", "generate_custom_solution"],
        approval_level="R2",
        disclosure_ceiling="D3",
        evidence_ids=["EVD-G-0120", "EVD-G-0125", "EVD-G-0228", "EVD-G-0236"],
    ),
    Policy(
        policy_id="POL-C-022",
        name="do_not_overclaim_root_cause_without_paired_evidence",
        rule_summary="没有问题稿+输入素材/母稿+平台提示等配对证据时，只能提出候选根因，不给确定处方。",
        trigger={},
        any_trigger=[
            {"request": ["root_cause_analysis", "platform_guarantee"]},
            {"corpus_reuse": ["high"]},
        ],
        judgment="candidate_root_cause_only",
        strategy="RESTRICT_DISCLOSURE",
        preferred_actions=["explain_tradeoff", "collect_real_samples"],
        restricted_actions=["definitive_prescription", "guarantee_outcomes"],
        approval_level="R1",
        disclosure_ceiling="D2",
        evidence_ids=["EVD-G-0098", "EVD-G-0099", "EVD-G-0110", "EVD-G-0111"],
    ),
]


def policy_by_id(policy_id: str) -> Policy:
    """Look up one canonical policy by id (raises KeyError on unknown id)."""
    return next(p for p in CANONICAL_POLICIES if p.policy_id == policy_id)
